version: '3.8'

services:
  baloncesto:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/baloncesto
      SPRING_DATASOURCE_USERNAME: usuario
      SPRING_DATASOURCE_PASSWORD: clave
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.28
    restart: always
    environment:
      MYSQL_DATABASE: baloncesto
      MYSQL_USER: usuario
      MYSQL_PASSWORD: clave
      MYSQL_ROOT_PASSWORD: test
    ports:
      - "3308:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8084:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: test
