name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker images
      run: |
        docker build . --file Dockerfile --tag omaraitlhouss1/webapp:latest
    - name: Log into Docker Hub
      run: echo "dckr_pat_sNHexFigLYYQrvAvbXPaiA5bXBQ" | docker login -u "omaraitlhouss1" --password-stdin

    - name:  push Docker images to Docker Hub
      run: |
        docker push omaraitlhouss1/webapp:latest
        
