name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker images
      run: |
        docker build . --file Dockerfile --tag omaraitlhouss1/webapp:latest
        

    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKE_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name:  push Docker images to Docker Hub
      run: |
        docker push omaraitlhouss1/webapp:latest
        
