name: baloncesto-pre 

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker images
        run: |
          docker build . --file Dockerfile --tag omaraitlhouss1/webapp:latest
    
      - name: Log into Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "omaraitlhouss1" --password-stdin

      - name: Push Docker images to Docker Hub
        run: |
          docker push omaraitlhouss1/webapp:latest

      - name: Install SSH client
        run: sudo apt-get install -y openssh-client 

      - name: SSH into Azure VM and echo message
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Login successful"

      
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy
        run: |
          docker rmi -f $(docker images -q)
          docker pull omaraitlhouss1/webapp:latest
          docker stop webapp
          docker rm webapp
          docker run -d -p 8083:8082 --name webapp omaraitlhouss1/webapp:latest


  qa:
    name: QA
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add QA steps here

      - name: Run QA tests
        run: |
          # Add commands to run QA tests here

      - name: Generate QA report
        run: |
          # Add commands to generate QA report here

