name: baloncesto-pre

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: self-hosted

    steps: 
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker images
        run: |
          docker build . --file Dockerfile --tag omaraitlhouss1/webapp:latest
    
      - name: Log into Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "omaraitlhouss1" --password-stdin

      - name: Push Docker images to Docker Hub
        run: |
          docker push omaraitlhouss1/webapp:latest

      - name: Install SSH client
        run: sudo apt-get install -y openssh-client 

      - name: SSH into Azure VM and echo message
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Login successful"
      
      - name: Check if container is running
        run: |
          if docker ps -a --format '{{.Names}}' | grep -Eq '^webapp$'; then
            docker stop webapp
          fi

      - name: Remove existing container (if any)
        run: |
          if docker ps -a --format '{{.Names}}' | grep -Eq '^webapp$'; then
            docker rm webapp
          fi

      - name: Pull latest Docker image
        run: docker pull omaraitlhouss1/webapp:latest

      - name: Run Docker container
        run: docker run -d -p 8083:8082 --name webapp omaraitlhouss1/webapp:latest
        # Add QA steps here

      - name: Generate QA report
        run: |
          if docker ps -f name=webapp --format '{{.Names}}' | grep -q webapp; then
            echo "Container is running"
          else
            echo "Container is not running"
            exit 1
          fi

      
