name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker images
      run: |
        docker build . --file Dockerfile --tag omaraitlhouss1/webapp:latest
    - name: Log into Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "omaraitlhouss1" --password-stdin

    - name:  push Docker images to Docker Hub
      run: |
        docker push omaraitlhouss1/webapp:latest
    - name: Install SSH client
      run: sudo apt-get install -y openssh-client 

    - name: SSH into Azure VM and echo message
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          echo "Login successful"
          docker rmi -f $(docker images -q)
          docker pull omaraitlhouss1/webapp:latest
          
          docker rm -f $(docker ps -q)

          docker run -d -p 8083:8082 omaraitlhouss1/webapp:latest

          
        
